server {
    listen 80;
    server_name localhost;

    # Directorio donde Nginx sirve el frontend
    root /usr/share/nginx/html;
    index index.html;

    # Regla para el Frontend (Vue Router History Mode)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para la API Backend
    location /api/ {
        # 'backend' es el nombre del servicio en docker-compose.yml
        proxy_pass http://backend:4000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Opcional: ajustar tiempos de espera si las DB queries son pesadas
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }
}
